events {}
http {
    server {
        listen       80; # Chạy trên cổng 80 thay cho IIS
        server_name  127.0.0.1;

        location / {
            proxy_pass http://127.0.0.1:6066; # Đẩy thẳng sang Python
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}